cc_test(
    name = "common_test",
    srcs = [
        "type_test.cc",
        "fixed_point_test.cc"
    ],
    deps = [
        "//src/primihub/common:common_lib",
        "@com_google_googletest//:gtest_main",
        "@com_google_absl//absl/base",
        "@com_google_absl//absl/flags:flag",
        "@com_google_absl//absl/flags:parse",
    ],
)