# Call this Dockerfile via the build_local.sh script
FROM primihub/primihub-base
RUN apt-get update \
    && apt-get -y install openjdk-8-jre-headless

WORKDIR /app

ADD bazel-bin.tar.gz ./
COPY src/primihub/protos/ src/primihub/protos/

RUN mkdir log \
  && cd python \
  && python3 setup.py develop

EXPOSE 50050
