package(default_visibility = ["//visibility:public"])
cc_library(
  name = "stream_data",
  hdrs = ["datastream_service.h"],
  srcs = ["datastream_service.cc"],
  deps = [
    "//src/primihub/protos:dataset_proto",
    "//src/primihub/node:node_impl",
    "//src/primihub/util:log_util",
    "//src/primihub/util:pb_log_helper",
  ],
)