cc_library(
    name = "config_lib",
    hdrs = [
        "config.h",
    ],
    srcs = [
        "config.cc",
    ],
    deps = [
        "//src/primihub/common:common_defination",
        "@com_github_jbeder_yaml_cpp//:yaml-cpp",
        "@com_github_glog_glog//:glog",
    ],
    visibility = ["//visibility:public"],
)