cc_test(
    name = "mpc_cmp_test",
    srcs = [
        "cmp_op_test.cc"
    ],
    deps = [
        "@com_google_googletest//:gtest_main",
        "@com_github_glog_glog//:glog",
        "//src/primihub/operator:aby3_operator",
        "@com_github_grpc_grpc//:grpc++",
    ],
)