cc_library(
    name = "microsoft_gsl",
    textual_hdrs = [
        "span",
        "gsl_assert",
        "gsl_util",
        "gsl_byte",
        "gsl_algorithm",
        "gsl",
        "multi_span",
        "string_span",
        "gls-lite.hpp",
    ],
    copts = [
        "--std=c++17",
    ],
    visibility = ["//visibility:public"],
)