package(default_visibility = ["//visibility:public",],)
cc_library(
  name = "sql_common_operation",
  hdrs = [
    "sql_driver_util.h",
  ],
  srcs = [
    "sql_driver_util.cc",
  ],
  deps = [
    "//src/primihub/common:common_defination",
    "@com_github_glog_glog//:glog",
    "@arrow",
    "@nlohmann_json",
  ],
)