cc_binary(
    name = "task_lib_test",
    srcs = [
        "fl_task_test.cc",
    ],
    deps = [
        "@com_google_googletest//:gtest_main",
        "@com_google_absl//absl/base",
        "@com_google_absl//absl/flags:flag",
        "@com_google_absl//absl/flags:parse",
        "//src/primihub/task/language:python_parser",
    ],
)