cc_test(
  name = "test_mpc_express_executor",
  srcs = [
      "express_test.cc"
  ],
  deps = [
      "//src/primihub/executor:mpc_express_executor",
      "@com_google_googletest//:gtest_main",
      "@com_github_grpc_grpc//:grpc++",
  ]
)