name: Sync to Gitee

on:
  push:
    branches:
      - develop

jobs:
  sync:
    runs-on: ubuntu-latest

    if: github.event.repository.fork == false

    steps:

    - name: Sync to Gitee
      uses: abersheeran/sync-gitee-mirror@v1-beta
      with:
        repository: primihub/${{ github.event.repository.name }}
        username: ${{ secrets.GITEE_USERNAME }}
        password: ${{ secrets.GITEE_PASSWORD }}