name: primihub arm build actions

on:
  push:
    branches:
    #  - master
    #  - develop
     - workflow # for test
    tags: [ '*.*.*' ]
  pull_request:
    branches: [ "master", "develop" ]

jobs:
  build-on-ubuntu-arm64:
    runs-on: [self-hosted, ARM64]
    steps:
    - uses: actions/checkout@v3
    - name: bazel build
      run: |
        # cc_binary
        bash pre_build.sh
        bazel build --config=linux_`arch` :node :py_main :cli :opt_paillier_c2py :linkcontext