name: primihub arm build actions

on:
  push:
    branches:
    #  - master
    #  - develop
     - workflow # for test
    tags: [ '*.*.*' ]
  pull_request:
    branches: [ "master", "develop" ]

jobs:
  build-on-ubuntu-arm64:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest ]
        arch: [ arm64 ]
    steps:
    - name: Install Dependencies
      run: |
         sudo apt update \
         && sudo apt install -y gcc-8 g++-8 python-dev cmake ninja-build libmysqlclient-dev \
         && sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-8 800 --slave /usr/bin/g++ g++ /usr/bin/g++-8
    - uses: actions/checkout@v3
    - name: Setup bazelisk
      uses: bazelbuild/setup-bazelisk@v2
    - name: set PYTHON LINK_OPTS
      run: ./pre_build.sh
      shell: bash
    - name: bazel build
      run: |
        # cc_binary
        mv -f WORKSPACE_GITHUB WORKSPACE
        bazel build --config=linux_`arch` :node :py_main :cli :opt_paillier_c2py :linkcontext